### ISSUE TITLE
probably want the github version of rmetasim

### ISSUE THREAD

**Issue by stranda** [EricArcher/EBV_Simulations#5]
First of all...Nice!  

Here is a suggestion that I think might prevent problems with downstream users:

I made a couple of changes to the rmetasim codebase in response to requests from Eric.  These are not reflected on CRAN at the moment.

Can the DESCRIPTION be changed to include a "Remotes:" section.  Something like

Remotes: stranda/rmetasim

devtools::install_github()  should install rmetasim from github rather than cran with this section installed.  At least I think/hope

**Comment by EricArcher** [comment]
Thanks so much for the suggestion! I didn't know about the "Remotes:" tag. I've added it for rmetasim and strataG.
